version: '3'

services:
  postgres:
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      APP_DB_USER: app_user
      APP_DB_PASS: app_pass
      APP_DB_NAME: app_db
    ports:
      - 5432:5432
    volumes:
      - ./postgres_db:/docker-entrypoint-initdb.d/
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - 8080:80
    volumes:
      - ./pgadmin_server_config.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    restart: unless-stopped
